version: '3.5'

services:
  php-eafpos-db:
    # mariadb: 10.5.9
    hostname: db
    container_name: php-eafpos-db
    build:
      context: docker/mariadb
      args:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./io:/appdata/io
      - ./docker/mariadb/scripts:/appdata/scripts
      - ./docker/mariadb/initdb:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - php-eafpos-net

  php-eafpos-cron:
    # crontab
    hostname: cron
    container_name: php-eafpos-cron
    build:
      context: docker/crontab
      args:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./io:/appdata/io
      - ./docker/crontab/scripts:/appdata/scripts
    depends_on:
      - php-eafpos-db
    networks:
      - php-eafpos-net

  php-eafpos-web:
    # nginx:latest
    hostname: nginx
    container_name: php-eafpos-web
    build:
      context: docker/nginx
    ports:
      - 900:90 #api
      - 901:91 #spa

      - 1000:100 #api sec
      - 1001:101 #spa sec

    volumes:
      - ./io:/appdata/io
      - ./backend_web/public:/appdata/www/backend_web/public
      - ./frontend/restrict/build:/appdata/www/frontend/restrict/build
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-eafpos-be
    networks:
      - php-eafpos-net

  php-eafpos-be:
    # php:7.4.16-fpm
    hostname: php
    container_name: php-eafpos-be
    build:
      context: docker/fpm
    environment:
      PHP_IDE_CONFIG: serverName=eafpos
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=gateway.docker.internal remote_port=9005
    volumes:
      - ./io:/appdata/io
      - ./backend_web:/appdata/www/backend_web
      - ./docker/fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    networks:
      - php-eafpos-net
      - mariadb-univ_net

networks:
  php-eafpos-net:
  mariadb-univ_net:
    external: true
